### ISSUE TITLE
Java exceptions

### ISSUE THREAD

**Issue by sunbc0120** [shadanan/HadoopLink#2]
```
link = OpenHadoopLink[
   "fs.default.name" -> "hdfs://hadoopheadlx.wolfram.com:8020",
   "mapred.job.tracker" -> "hadoopheadlx.wolfram.com:8021"];

DFSFileNames[link]
```

```
Java::excptn: A Java exception occurred: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FileSystem
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249).

LoadJavaClass::fail: Java failed to load class org.apache.hadoop.fs.FileSystem. >>

Java::excptn: A Java exception occurred: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249).

LoadJavaClass::fail: Java failed to load class org.apache.hadoop.conf.Configuration. >>

KeepJavaObject::obj: At least one argument to KeepJavaObject was not a valid Java object. >>

Java::excptn: A Java exception occurred: java.lang.ClassNotFoundException: org.apache.hadoop.fs.Path
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249).

General::stop: Further output of Java::excptn will be suppressed during this calculation. >>

LoadJavaClass::fail: Java failed to load class org.apache.hadoop.fs.Path. >>

General::stop: Further output of LoadJavaClass::fail will be suppressed during this calculation. >>

StringMatchQ::strse: String or list of strings expected at position 1 in StringMatchQ[OperatingSystem->Unix,*]. >>

```

**Comment by sunbc0120** [comment]
This problem is solved by (1) include java path to system environment; (2) have MMA's java version be compatible with OS.
